// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosaC-5wQ5eZGMm1lkXpnm-bULehYb9UM',
    appId: '1:829057696605:web:e24f1577cb714ff8dedeb4',
    messagingSenderId: '829057696605',
    projectId: 'budgetapp-5747c',
    authDomain: 'budgetapp-5747c.firebaseapp.com',
    storageBucket: 'budgetapp-5747c.appspot.com',
    measurementId: 'G-WM2NTTDJ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQstjeKKhWOMHi9B0Kio_P-FbbAuAmEEc',
    appId: '1:829057696605:android:b200913114e77548dedeb4',
    messagingSenderId: '829057696605',
    projectId: 'budgetapp-5747c',
    storageBucket: 'budgetapp-5747c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsS2W3roDIV4S_QQzdl1otDCNzC7akUw4',
    appId: '1:829057696605:ios:4a0c705acce7dafddedeb4',
    messagingSenderId: '829057696605',
    projectId: 'budgetapp-5747c',
    storageBucket: 'budgetapp-5747c.appspot.com',
    iosClientId: '829057696605-eqequdksq5ac0223v75nvejof5leshmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp',
  );
}
